GLOBAL.PATH_ROOT = __dirname + '/../';

GLOBAL.PATH_SERVER = PATH_ROOT + 'server/';
GLOBAL.PATH_MODULES = PATH_SERVER + 'modules/';
GLOBAL.PATH_CONFIGS = PATH_MODULES + 'configs/';
GLOBAL.PATH_CONTROLLERS = PATH_MODULES + 'controllers/';
GLOBAL.PATH_MANAGERS = PATH_MODULES + 'managers/';
GLOBAL.PATH_MODELS = PATH_MODULES + 'models/';
GLOBAL.PATH_SERVICES = PATH_MODULES + 'services/';

GLOBAL.PATH_CLIENT = PATH_ROOT + 'client/';
GLOBAL.PATH_BUILD = PATH_CLIENT + 'build/';
GLOBAL.PATH_BIN = PATH_CLIENT + 'bin/';

GLOBAL.ENCODING = 'utf8';
